export const INITIAL_POKEMON = [
  {
    "id": 1,
    "name": "bulbasaur",
    "types": ["grass", "poison"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png",
    "height": 7,
    "weight": 69,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 45, "attack": 49, "defense": 49, "specialAttack": 65, "specialDefense": 65, "speed": 45 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 2,
    "name": "ivysaur",
    "types": ["grass", "poison"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png",
    "height": 10,
    "weight": 130,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 60, "attack": 62, "defense": 63, "specialAttack": 80, "specialDefense": 80, "speed": 60 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 3,
    "name": "venusaur",
    "types": ["grass", "poison"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png",
    "height": 20,
    "weight": 1000,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 80, "attack": 82, "defense": 83, "specialAttack": 100, "specialDefense": 100, "speed": 80 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 4,
    "name": "charmander",
    "types": ["fire"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png",
    "height": 6,
    "weight": 85,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 39, "attack": 52, "defense": 43, "specialAttack": 60, "specialDefense": 50, "speed": 65 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 5,
    "name": "charmeleon",
    "types": ["fire"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png",
    "height": 11,
    "weight": 190,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 58, "attack": 64, "defense": 58, "specialAttack": 80, "specialDefense": 65, "speed": 80 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 6,
    "name": "charizard",
    "types": ["fire", "flying"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png",
    "height": 17,
    "weight": 905,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 78, "attack": 84, "defense": 78, "specialAttack": 109, "specialDefense": 85, "speed": 100 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 7,
    "name": "squirtle",
    "types": ["water"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png",
    "height": 5,
    "weight": 90,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 44, "attack": 48, "defense": 65, "specialAttack": 50, "specialDefense": 64, "speed": 43 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  },
  {
    "id": 8,
    "name": "wartortle",
    "types": ["water"],
    "imageUrl": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png",
    "height": 10,
    "weight": 225,
    "isLegendary": false,
    "isMythical": false,
    "stats": { "hp": 59, "attack": 63, "defense": 80, "specialAttack": 65, "specialDefense": 80, "speed": 58 },
    "abilities": [],
    "flavorText": "",
    "relations": { "doubleDamageFrom": [], "halfDamageFrom": [], "noDamageFrom": [] }
  }
];
